<?php

  global $txt;

  $txt['section'] = 'Section';
  $txt['sections'] = 'Sections';
  $txt['pps_forum'] = 'PPS Forum';
  $txt['pps_portal'] = 'PPS Portal';
  $txt['support_title'] = 'Support';
  $txt['support_text'] = 'Ab sofort kannst Du Dich mit allen Fragen im Zusammenhang mit der Piratenpartei an <a href="mailto:support@piratenpartei.ch">support@piratenpartei.ch</a> wenden.';
  $txt['latest_news'] = 'Latest News';
  $txt['chat'] = 'Chat';
  $txt['users_online'] = 'User Online'; 

  $txt['ignore_no_boards'] = "Momentan werden keine Foren ausgeblendet";
  $txt['ignore_following_boards'] = "Folgende Foren sind momentan ausgeblendet: ";
  $txt['configure_ignore_boards'] = "Wenn du das &auml;nder m&ouml;chtest:";
  $txt['configure_here'] = "hier kannst du das konfigurieren";
?>

