<?php

  global $txt;

  $txt['section'] = 'Section';
  $txt['sections'] = 'Sections';
  $txt['pps_forum'] = 'PPS Forum';
  $txt['pps_portal'] = 'PPS Portal';
  $txt['support_title'] = 'Support';
  $txt['support_text'] = 'Ab sofort kannst Du Dich mit allen Fragen im Zusammenhang mit der Piratenpartei an <a href="mailto:support@piratenpartei.ch">support@piratenpartei.ch</a> wenden.';
  $txt['latest_news'] = 'Latest News';
  $txt['chat'] = 'Chat';
  $txt['users_online'] = 'User Online'; 

  $txt['ignore_no_boards'] = "Currently you ignore no boards.";
  $txt['ignore_following_boards'] = "Currently you ignore the following boards: ";
  $txt['configure_ignore_boards'] = "If you want to change that:";
  $txt['configure_here'] = "configure here";
?>

